apiVersion: apps/v1
kind: Deployment
metadata:
  name: legoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legoapp
  template:
    metadata:
      labels:
        app: legoapp
    spec:
      containers:
        - name: legoapp
          image: cc2526acr.azurecr.io/lego-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MEDIA_PATH
              value: /media
            - name: DB_URL
              value: mongodb://admin:senhaSegura123@mongodb-service:27017/ccdb?authSource=admin
            - name: DB_NAME
              value: ccdb
            # se quiser desligar Cosmos de vez:
            - name: DB_KEY
              value: ""    #não necessário Mongo
          volumeMounts:
            - name: media-volume
              mountPath: /media
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
