apiVersion: apps/v1
kind: Deployment
metadata:
  name: legoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legoapp
  template:
    metadata:
      labels:
        app: legoapp
    spec:
      containers:
        - name: legoapp
          image: cc2526acr.azurecr.io/lego-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # --- CONFIGURAÇÃO DO VOLUME ---
            - name: MEDIA_PATH
              value: /media
            - name: DB_URL
              value: mongodb://admin:senhaSegura123@mongodb-service:27017/ccdb?authSource=admin
            - name: DB_NAME
              value: ccdb
            # se quiser desligar Cosmos de vez:
            - name: DB_KEY
              value: ""    #não necessário Mongo

            # --- REDIS LOCAL (K8s Service) ---
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: REDIS_KEY
              value: ""

            # --- VARIÁVEIS DE PRODUÇÃO ---
            - name: DB_KEY
              valueFrom:
                secretKeyRef:
                  name: lego-app-secrets
                  key: DB_KEY
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: lego-app-secrets
                  key: DB_NAME
            - name: BlobStoreConnection
              valueFrom:
                secretKeyRef:
                  name: lego-app-secrets
                  key: BlobStoreConnection
            - name: AZURE_STORAGE_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: lego-app-secrets
                  key: AZURE_STORAGE_CONTAINER

          # --- VOLUMES E MONTAGENS ---
          volumeMounts:
            - name: media-volume
              mountPath: /media
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /rest/ctrl/version
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
