apiVersion: apps/v1
kind: Deployment
metadata:
  name: legoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legoapp
  template:
    metadata:
      labels:
        app: legoapp
    spec:
      containers:
        - name: legoapp
          image: <TEU_DOCKERHUB>/cc2526-app:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: media-volume
              mountPath: /media
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
